title: 'Ministry of Law - Insolvency Office'
description: Description
url: 'https://io.mlaw.gov.sg'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
    - jekyll-feed
    - jekyll-assets
    - jekyll-paginate
    - jekyll-sitemap
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
collections:
    bankruptcy-and-debt-repayment-scheme:
        output: true
    corporate-insolvency:
        output: true
    about-us:
        output: true
    bankruptcy:
        output: true
    debt-repayment-scheme:
        output: true
    unclaimed-monies:
        output: true
    e-services:
        output: true
    News:
        output: true
favicon: /images/favicon-minlaw.ico
google-analytics: UA-10405444-14
permalink: none
baseurl: ""
defaults:
    - scope:
          path: ""
      values:
          layout: page
