title: Ministry of Law - Insolvency Office
title-abbreviated: Ministry of Law - Insolvency Office
description: >- # this means to ignore newlines until "baseurl:"
  Description
url: "https://io.mlaw.gov.sg"

# Build settings
markdown: kramdown
remote_theme: isomerpages/isomerpages-template
safe: false

plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sitemap

# Breadcrumbs
breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

# Resource Room and Pagination
paginate: 12

# Homepage sections
homepage_hero_i_want_to: false
homepage_resources: false

# Feedback Form URL
feedback_form_url: "https://eservices.mlaw.gov.sg/enquiry/"

# FAQ URL
faq_url: "https://va.ecitizen.gov.sg/cfp/customerPages/mlaw/explorefaq.aspx"
faq_url_external: true

# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"

collections:
  bankruptcy-and-debt-repayment-scheme:
    output: true
  corporate-insolvency:
    output: true
  about-us:
    output: true
  bankruptcy:
    output: true
  debt-repayment-scheme:
    output: true
  corporate-insolvency:
    output: true
  unclaimed-monies:
    output: true
  e-services:
    output: true
  News :
    output: true
